INSERT INTO CATEGORIA (ID, DESCRICAO) VALUES (nextval('hibernate_sequence'), 'Quadrinhos');
INSERT INTO CATEGORIA (ID, DESCRICAO) VALUES (nextval('hibernate_sequence'), 'Filmes');
INSERT INTO CATEGORIA (ID, DESCRICAO) VALUES (nextval('hibernate_sequence'), 'Livros');

INSERT INTO FORNECEDOR (ID, CNPJ, RAZAO_SOCIAL) VALUES (nextval('hibernate_sequence'), '93.550.007/0001-68', 'Loja de Quadrinhos Mega Massa');
INSERT INTO FORNECEDOR (ID, CNPJ, RAZAO_SOCIAL) VALUES (nextval('hibernate_sequence'), '60.199.184/0001-92', 'Loja de Filmes Mega Massa');
INSERT INTO FORNECEDOR (ID, CNPJ, RAZAO_SOCIAL) VALUES (nextval('hibernate_sequence'), '74.796.391/0001-39', 'Loja de Livros Mega Massa');

INSERT INTO PRODUTO (ID, DESCRICAO, FK_CATEGORIA, FK_FORNECEDOR, QTD_ESTOQUE, DISPONIBILIDADE, DATA_CADASTRO) VALUES (nextval('hibernate_sequence'), 'Crise nas Infinitas Terras', 1, 4, 3, 'DISPONIVEL', CURRENT_TIMESTAMP);
INSERT INTO PRODUTO (ID, DESCRICAO, FK_CATEGORIA, FK_FORNECEDOR, QTD_ESTOQUE, DISPONIBILIDADE, DATA_CADASTRO) VALUES (nextval('hibernate_sequence'), 'O Homem de Aço', 2, 5, 5, 'DISPONIVEL', CURRENT_TIMESTAMP);
INSERT INTO PRODUTO (ID, DESCRICAO, FK_CATEGORIA, FK_FORNECEDOR, QTD_ESTOQUE, DISPONIBILIDADE, DATA_CADASTRO) VALUES (nextval('hibernate_sequence'), 'Os Últimos Dias de Krypton', 3, 6, 4, 'DISPONIVEL', CURRENT_TIMESTAMP);
INSERT INTO PRODUTO (ID, DESCRICAO, FK_CATEGORIA, FK_FORNECEDOR, QTD_ESTOQUE, DISPONIBILIDADE, DATA_CADASTRO) VALUES (nextval('hibernate_sequence'), 'Watchmen Edição Definitiva', 1, 4, 3, 'DISPONIVEL', CURRENT_TIMESTAMP);
INSERT INTO PRODUTO (ID, DESCRICAO, FK_CATEGORIA, FK_FORNECEDOR, QTD_ESTOQUE, DISPONIBILIDADE, DATA_CADASTRO) VALUES (nextval('hibernate_sequence'), 'Watchmen O Filme', 2, 5, 5, 'DISPONIVEL', CURRENT_TIMESTAMP);
INSERT INTO PRODUTO (ID, DESCRICAO, FK_CATEGORIA, FK_FORNECEDOR, QTD_ESTOQUE, DISPONIBILIDADE, DATA_CADASTRO) VALUES (nextval('hibernate_sequence'), 'Coração de Tinta', 3, 6, 8, 'DISPONIVEL', CURRENT_TIMESTAMP);